### PR TITLE
Adf feature data/liu yang

### PR DESCRIPTION
**Pull request by ly5918**
20240709_ADF If using batch mode, pipeline should be linked to a batch else raise error.

### CODE REVIEW

**Comment by ly5918** [comment]
If using batch mode, pipeline should be linked to a batch else raise error.

**Comment by ly5918** [comment]
If using batch mode, pipeline should be linked to a batch else raise error.

**Comment by ly5918** [comment]
If using batch mode, pipeline should be linked to a batch else raise error.

**Comment by luyanAAAA** [comment]
ok

**Review by luyanAAAA — APPROVED** [review]

**Pull request merged**
